### ISSUE TITLE
Uncaught ReferenceError on file save

### ISSUE THREAD

**Issue by MaksimZh** [LaurentTreguier/ide-dlang#1]
1. `$ mkdir foo && touch foo/foo.d && atom foo`
2. Open foo.d
3. Press Ctrl+S

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Linux Mint
**Thrown From**: [ide-dlang](https://github.com/LaurentTreguier/ide-dlang) package 1.5.1

### Stack Trace

Uncaught ReferenceError: basename is not defined

```
At /home/maksim/.atom/packages/ide-dlang/lib/ide-dlang.js:40

ReferenceError: basename is not defined
    at DLSLanguageClient.filterChangeWatchedFiles (/packages/ide-dlang/lib/ide-dlang.js:40:67)
    at /packages/ide-dlang/node_modules/atom-languageclient/build/lib/auto-languageclient.js:189:166)
    at ServerManager.projectFilesChanged (/packages/ide-dlang/node_modules/atom-languageclient/build/lib/server-manager.js:251:81)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/usr/share/atom/resources/app/src/project.js:381:28)
    at PathWatcher.onNativeEvents (/usr/share/atom/resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/usr/share/atom/resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NSFWNativeWatcher.onEvents (/usr/share/atom/resources/app/src/path-watcher.js:167:24)
    at handler (/usr/share/atom/resources/app/src/path-watcher.js:276:18)
```

### Commands

```
     -0:04.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
ide-dlang 1.5.1 
selection-mode 0.2.1 
```

**Comment by LaurentTreguier** [comment]
This should have been closed by #2...
