### ISSUE TITLE
Failed to load a ide-dlang package grammar

### ISSUE THREAD

**Issue by jamadagni** [LaurentTreguier/ide-dlang#4]
[Enter steps to reproduce:]

Hello. Got this error right after my first time of installing this package (on a brand new Atom installation). So I didn't ‘do’ anything to cause it!

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: [ide-dlang](https://github.com/LaurentTreguier/ide-dlang) package 1.7.3

### Stack Trace

Failed to load a ide-dlang package grammar

```
At Grammar missing required scopeName property: /home/samjnaa/.atom/packages/ide-dlang/grammars/d.configuration.json in /home/samjnaa/.atom/packages/ide-dlang/grammars/d.configuration.json

Error: Grammar missing required scopeName property: /home/samjnaa/.atom/packages/ide-dlang/grammars/d.configuration.json
    at GrammarRegistry.createGrammar (/usr/share/atom/resources/app/src/grammar-registry.js:501:21)
    at CSON.readFile (/usr/share/atom/resources/app/src/grammar-registry.js:480:35)
    at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:123:13)
    at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:230:26
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
  at /packages/ide-dlang/grammars/d.configuration.json:1:1
```

### Commands

```
     -0:15.4.0 pane:show-next-item (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
autocomplete-python 1.10.9 
ide-bash 1.0.11 
ide-clangd 0.3.0 
ide-dlang 1.7.3 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 1.0.0 
ide-yaml 0.4.3 
python-indent 1.1.5 
python-tools 0.6.9 
script 3.18.1 
```

**Comment by LaurentTreguier** [comment]
It should be alright with `v1.7.4`. That configuration file should never have gotten here in the first place, it's for VSCode... I must have copied the wrong file when trying to update the grammar at some point.
